### PR TITLE
feat: pass data to partial

### PR DESCRIPTION
**Pull request by philicevic**
As other people already mentioned, it would be nice to be able to pass data from the template into a partial:

Template:
```
<include src="file.html" data='{
    "text": "Text"
}'></include>
```

Partial:
```
<h1>{{ text }}</h1>
```

Output:
```
<h1>Text</h1>
```

This feature can be achieved using the [posthtml-expressions](https://github.com/posthtml/posthtml-expressions/) package, that's what i have done here.

There have been similar closed issues, but their solutions don't really work in every case.
Two examples:

#32: While using `posthtml-modules` you can't pass multiple variables

#8: If I wanted to write my own plugin here, i would basically just copy `posthtml-include` and add these few lines. So why don't just add it to the package as an optional feature?

### CODE REVIEW

**Comment by Scrum** [comment]
@philicevic Hi, It looks very cool, can I add a description of this option to the documentation?

**Comment by Scrum** [comment]
Ideally, it’s better to pull out the tipping mechanism `data to partial`

**Comment by philicevic** [comment]
Thanks @Scrum,

I added the option to the README (and fixed a line in the output).

However I don't really get what you mean with:

> Ideally, it’s better to pull out the tipping mechanism `data to partial`

But it's probably me :D

**Comment by Scrum** [comment]
> However I don't really get what you mean with:

so as not to use the whole plugin only the part responsible for data interpolation will be used, so it would be pulled into the current plugin

**Comment by philicevic** [comment]
Oh, My bad.
I will look into it and update the pull request later!

**Comment by Scrum** [comment]
> I will look into it and update the pull request later!

Take your time, this is just an offer))

**Comment by Scrum** [comment]
@philicevic  I will publish it tomorrow, thanks for your interest in our products, it is important for us.

**Comment by Scrum** [comment]
@philicevic I changed the parameter name `data` to `locals` perhaps in the future it is worth considering the incoming options for `posthtml-expression`

**Comment by Scrum** [comment]
@philicevic publish v1.4.0

**Comment by philicevic** [comment]
Great! Thanks a lot @Scrum ! 😁

**Pull request merged**
